### ISSUE TITLE
"Another" bug with generate Heightmap

### ISSUE THREAD

**Issue by hoaxhoax** [Jay2645/Unreal-Polygonal-Map-Gen#14]
When i create heightmap with too "high" resolution size ->= 250 for me. I ve got an error and close the editor.

`Assertion failed: !AllocationFlags[Index] [File:D:\Epic Games\UE_4.16\Engine\Source\Runtime\Core\Public\Containers/SparseArray.h] [Line: 78] 

KERNELBASE
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_MyGame_2480!TSparseArray<TSetElement<TTuple<FVector2D,int> >,TSparseArrayAllocator<FDefaultAllocator,FDefaultBitArrayAllocator> >::AllocateIndex() [d:\epic games\ue_4.16\engine\source\runtime\core\public\containers\sparsearray.h:81]
UE4Editor_MyGame_2480!TSet<TTuple<FVector2D,int>,TDefaultMapHashableKeyFuncs<FVector2D,int,0>,FDefaultSetAllocator>::Emplace<TPairInitializer<FVector2D const & __ptr64,int const & __ptr64> >() [d:\epic games\ue_4.16\engine\source\runtime\core\public\containers\set.h:490]
UE4Editor_MyGame_2480!UPolygonMap::FindMapCenterForCoordinate() [d:\unreal projects\mygame\source\mygame\private\map\polygonmap.cpp:412]
UE4Editor_MyGame_2480!FHeightmapPointTask::MakeMapPoint() [d:\unreal projects\mygame\source\mygame\private\map\heightmap\heightmappointtask.cpp:245]
UE4Editor_MyGame_2480!FHeightmapPointTask::DoTask() [d:\unreal projects\mygame\source\mygame\private\map\heightmap\heightmappointtask.cpp:282]
UE4Editor_MyGame_2480!TGraphTask<FHeightmapPointTask>::ExecuteTask() [d:\epic games\ue_4.16\engine\source\runtime\core\public\async\taskgraphinterfaces.h:883]
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
kernel32
ntdll`

In low resolution, you could see that there is many many many many warning "LogWorldGen:Warning: Tried to fetch a pixel at 227, 123, but no pixel was found.", Don't know if it could help you. After a few execution, you could see that editor get a new error

`Access violation - code c0000005 (first/second chance not available)
VCRUNTIME140
UE4Editor_GameplayTags
UE4Editor_GameplayTags
UE4Editor_GameplayTags
UE4Editor_MyGame_2480!TArray<FMapData,FDefaultAllocator>::CopyToEmpty<FMapData>() [d:\epic games\ue_4.16\engine\source\runtime\core\public\containers\array.h:2323]
UE4Editor_MyGame_2480!UPolygonalMapHeightmap::CheckMapPointsDone() [d:\unreal projects\mygame\source\mygame\private\map\heightmap\polygonalmapheightmap.cpp:33]
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_MyGame_2480!UE4Function_Private::TFunctionRefCaller<<lambda_57bf9da02145909c0e8c545268c2f5d5>,void __cdecl(void)>::Call() [d:\epic games\ue_4.16\engine\source\runtime\core\public\templates\function.h:244]
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Engine
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll`

**Comment by hoaxhoax** [comment]
Remake fresh install of unreal engine & plugin, do the same thing. Can't create heightmap.

**Comment by hoaxhoax** [comment]
I remove multi thread system, and it stop to bug. Of course it s slower than multi thread

**Comment by Streliteela** [comment]
Hi, 
so so so Sorry to bother you ...
Could you tell me how to call out the delegate OnGenerationComplete showed in the ExampleProject ?
![bfde088c-fb9d-11e6-9ec4-7d5ef6792a6c](https://user-images.githubusercontent.com/13235660/28614374-373c532e-7228-11e7-9df7-ecb45388afe9.jpg)

I am a freasher on UE4. 
Any help is appreciated :-)

**Comment by hoaxhoax** [comment]
Just create a new line from on complete and add custom event. You could call it On Generation Complete

**Comment by Streliteela** [comment]
@hoaxhoax 

Many thanks for the prompt reply.

And, could you provide me some information?

This plugin doesn't work on UE4.16 ?  Every time I run the ExampleProject provided, the UE4.16 editor crashes without any message just popping up the window:

![1](https://user-images.githubusercontent.com/13235660/28658378-9f1569e4-72dd-11e7-95ca-d1d54af956ec.png)

I have no idea about this :-(

In my own project, create new level, draw Even Graph in Level BluePrint as follows, 

![2](https://user-images.githubusercontent.com/13235660/28659503-47f549ea-72e2-11e7-8363-d44fb8675511.png)

However, there is nothing when I click "Play". It indeed notified the "On Generation Complete" event since the string was shown in the screen. The editor crashed frequently. 

Any assistant you can provide would be greatly appreciated :-)

**Comment by hoaxhoax** [comment]
I never see that bug and i think that the author doesn't support it anymore. You should try to do it by yourself.

**Comment by Streliteela** [comment]
@hoaxhoax 
Thank you anyway :-)

**Comment by Jay2645** [comment]
Sorry I haven't had time to reply; I've been in the process of moving house for the past month and have only recently (as in the last week) even had a stable internet connection (stupid AT&T). In the process, GitHub has decided to mark my account as a spam account (really??), so I'm not even sure if you can see my comments anymore.

I do know that `GenerateHeightmap` is a super-buggy function, and one that I don't personally even use anymore. I do have plans to improve it, but I've been too busy getting adjusted to my new place and working on a different part of the project. You can look at the code to see that it's pretty much made of spaghetti -- I literally sample every single `MapData` struct and try to get the *n* closest neighbors. At higher resolutions, this can take ***ages***, which is why I moved to a multithreaded system, which... isn't quite as stable.

I do have an improved version of `PolygonMap` which is able to determine which triangle a given pixel belongs to. It's not been pushed up to Master yet, but I'll see what I can do about ensuring everything is working on 4.16.2 and pushing it up either tonight or tomorrow. With that change, I'll be able to fix `GenerateHeightmap` to at least be more reliable, even though the generated heightmap would be a little "blocky".

**Comment by Jay2645** [comment]
I think I've fixed the issue with commit https://github.com/Jay2645/Unreal-Polygonal-Map-Gen/commit/05f1ff523411e7c336fa33320cfae20e2da6cc5c. I'm closing this for now. Feel free to reopen it if you're still having issues!
