### ISSUE TITLE
Crash on create heightmap in background

### ISSUE THREAD

**Issue by hoaxhoax** [Jay2645/Unreal-Polygonal-Map-Gen#16]
Hello, thanks for the last fix!!

Now i try the new version, this is my blueprint to create heightmap.
![byhz-qn0qdqeukuecebvyq](https://user-images.githubusercontent.com/28735281/29002328-0665cea8-7aa0-11e7-82c4-915f933ef1a7.png)
But when you change the heightmap generation options to background, it crash with this unknow message:
![a3yns1frt4kub1mgm5jcow](https://user-images.githubusercontent.com/28735281/29002340-5a1f9b1e-7aa0-11e7-8b34-798e552cc83e.png)

This is heightmap that plugin produce:
![ydvnfxtirqemz-49mxikba](https://user-images.githubusercontent.com/28735281/29002349-93340c5a-7aa0-11e7-8cd4-6179742a41f4.png)
I see in your PolygonalMapHeightmap, you select a method to create each point (EPointSelectionMode). You can't change mode from blueprint, right? I decide to change method and change EPointSelectionMode::InterpolatedWithPolygonBiome to Interpolated and the result is the same the other.
![interpolate](https://user-images.githubusercontent.com/28735281/29002377-7c011f40-7aa1-11e7-885f-8d3424515c9d.png)
Is heightmap generation is good?

Thanks!

**Comment by Jay2645** [comment]
Hmm. Interesting. Unfortunately, I can't really debug it unless you have
debugging symbols installed, since the same setup works on my end.

Are you able to install them? There's a walkthrough on doing it here:
https://answers.unrealengine.com/questions/382003/you-do-not-have-any-debugging-symbols-required-to.html

Note that it's a fairly large install, so I understand if you have a
metered connection or hard drive space is a premium. Once they're
installed, that error message should print out the callstack that causes
the crash, so I can trace it down to the exact line.

"Background" uses a task graph, which I worked really hard to get stable,
but still has a few issues. That task graph is probably what's making it go
wrong, but I won't be able to work out where unless I can get the stack
trace from the crash.

The reason why I don't have an option to easily change the
EPointSelectionMode is because of issue #12 causing it to crash sometimes.
Once I work out what's going on there, I'll add a setting to set
EPointSelectionMode from blueprint.

As for the actual heightmap, I'm not 100% sure what's going on there. I just tried it and got similar results. I'll poke around the code and see what I can do.

**Comment by hoaxhoax** [comment]
I add it to my engine. This is the trace
![fail](https://user-images.githubusercontent.com/28735281/29007138-43b82a78-7afd-11e7-8d50-d969d5199c44.png)

I see that speak about adding element to gameplaytag, here screenshot to be sure that i add them to my project
![tag](https://user-images.githubusercontent.com/28735281/29007155-8f290b6c-7afd-11e7-892e-19dc79359fde.png)

**Comment by Jay2645** [comment]
As suspected, it is something related to issue #12. Here's the rundown as to what's going on:

The issue is happening when the engine attempts to copy our Biome into our heightmap. [This is the function where that happens](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/GameplayTags/Private/GameplayTagContainer.cpp#L493).

The issue comes up on line 504, when they copy the parent tags from our Biome's GameplayTag. That calls the Append function on the parent tags array, [which can be found here](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Core/Public/Containers/Array.h#L1637). It's saying the issue comes on line 1653, but I think it's actually happening on line 1651, and the engine doesn't realize anything is wrong until it attempts to run line 1653. It's trying to construct another copy of the GameplayTag to append to the array (I think), and it runs into a memory issue of some kind and the engine crashes.

I'm just going to move the biome assignment to be done on the main thread after all the actual heightmap stuff is done. Hopefully that should solve the problem. I'll try and push a fix tonight once I get home.

**Comment by Jay2645** [comment]
So hopefully commit https://github.com/Jay2645/Unreal-Polygonal-Map-Gen/commit/677901c9cb12a359a678f758ef9860a86b6981ec has fixed your crash bug. Let me know if you still have issues. Note that there might be a slight performance drop, as biome determination got put back on the game thread.

Additionally, the heightmaps generated should look a lot better now:
![testheightmap](https://user-images.githubusercontent.com/2058763/29061252-e7f47900-7bd1-11e7-9ff4-c6bde643d0ef.png)
You can still see the sharp "edges" of each triangle on the heightmap, but overall it should look better than the psychedelic heightmaps you were getting. It turns out that rather than being in the range 0-1, when I was working out the pixel's height I was actually setting them to some pretty insane values. Now everything should be normalized and work fine.

Give it a whirl and feel free to reopen this issue if it's still crashing.
