### ISSUE TITLE
Square points generator has invalid triangles

### ISSUE THREAD

**Issue by MichMW** [Jay2645/Unreal-Polygonal-Map-Gen#18]
Delanauy has some invalid edges on the side of map (on the border) when using the square points generator.

**Comment by Jay2645** [comment]
I'll take a look when I get back to my PC later tonight.

**Comment by MichMW** [comment]
its visible with from 200 - 300 points. Lower points have somehow working edges.

**Comment by MichMW** [comment]
@Jay2645 havnt heared from you anymore?

**Comment by Jay2645** [comment]
I'm not able to replicate the problem, sadly.

This is with 1500 points:
![screenshot 2](https://user-images.githubusercontent.com/2058763/32363024-66a2b428-c02a-11e7-911b-12b0f8e8dd16.png)
And this is 400 points:
![screenshot 3](https://user-images.githubusercontent.com/2058763/32363028-6a6a0336-c02a-11e7-9993-d2621ce20c2b.png)

The different colors are due to the different biomes, since I'm using a WhittakerBiomeManager here.

**Comment by Jay2645** [comment]
I'm going to go ahead and close this issue, with the note that I'm completely rewriting the code from scratch. I've created a new branch with all the changes, which you can see [here](https://github.com/Jay2645/Unreal-Polygonal-Map-Gen/tree/refactor). It's designed to compile with Unreal Engine 4.21; I can't make promises regarding compatibility with older versions.

It's not quite up to parity yet, but it generates islands and has an option to procedurally create meshes. Hopefully I'll be able to bring it up to feature parity sooner rather than later.
